In [1]:
import numpy as np
import pandas as pd
import requests
import copy

# Valores Importantes de definição do primeiro Desembolso:

In [36]:
Valor = 20200000
Tempo = 144
TaxaJuros = ((1 + 0.1225)**(1/12)-1 )* 100
print('taxa de juros mensal a ser adicionada ao IPCA:',TaxaJuros)
DataDesembolso = '15-02-2024'
DataPagamento = '15-03-2024'

taxa de juros mensal a ser adicionada ao IPCA: 0.9676378033213417

## Rodando Serviço:

In [3]:
url = f'https://install-app-prod.hmg.gyramais.com.br/installapp/priceTableTabular/?preApproved={Valor}&Period={Tempo}&interestRate={TaxaJuros}&DisbursementDate={DataDesembolso}&PaymentDate={DataPagamento}&Partner=Gyra&IPCA=True&Fees=False&Iof=False&AdjustedIof=True'

In [4]:
_json_ = requests.get(url)

In [7]:
df = pd.json_normalize(_json_.json())

## Tabela Price:

In [8]:
df

,DisbursementDate,IPCA,Iof,amortization_amount,annualCet,balance,installAmount,installDates,interest,interestRate,months,number,payDayDates,preApproved,preApprovedWithFees,principal,totalFinalAmount
0,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,20083104.18,321951.84,"Fri, 15 Mar 2024 00:00:00 GMT",263503.93,0.013498,144,1,"Fri, 15 Mar 2024 00:00:00 GMT",20200000.0,20200000.0,58447.91,46361064.96
1,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,20059623.26,321951.84,"Mon, 15 Apr 2024 00:00:00 GMT",280987.42,0.013498,144,2,"Mon, 15 Apr 2024 00:00:00 GMT",20200000.0,20200000.0,40964.42,46361064.96
2,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,19999302.99,321951.84,"Wed, 15 May 2024 00:00:00 GMT",271309.50,0.013498,144,3,"Wed, 15 May 2024 00:00:00 GMT",20200000.0,20200000.0,50642.34,46361064.96
3,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,19965460.56,321951.84,"Sat, 15 Jun 2024 00:00:00 GMT",279709.45,0.013498,144,4,"Mon, 17 Jun 2024 00:00:00 GMT",20200000.0,20200000.0,42242.39,46361064.96
4,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,19903910.83,321951.84,"Mon, 15 Jul 2024 00:00:00 GMT",270055.78,0.013498,144,5,"Mon, 15 Jul 2024 00:00:00 GMT",20200000.0,20200000.0,51896.06,46361064.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,943439.84,321951.84,"Mon, 15 Oct 2035 00:00:00 GMT",20862.14,0.013498,144,140,"Mon, 15 Oct 2035 00:00:00 GMT",20200000.0,20200000.0,301089.70,46361064.96
140,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,635349.82,321951.84,"Thu, 15 Nov 2035 00:00:00 GMT",17361.98,0.013498,144,141,"Thu, 15 Nov 2035 00:00:00 GMT",20200000.0,20200000.0,304589.86,46361064.96
141,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,321409.85,321951.84,"Sat, 15 Dec 2035 00:00:00 GMT",12686.92,0.013498,144,142,"Mon, 17 Dec 2035 00:00:00 GMT",20200000.0,20200000.0,309264.92,46361064.96
142,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,4367.71,321951.84,"Tue, 15 Jan 2036 00:00:00 GMT",8798.31,0.013498,144,143,"Tue, 15 Jan 2036 00:00:00 GMT",20200000.0,20200000.0,313153.53,46361064.96
143,"Thu, 15 Feb 2024 00:00:00 GMT",0.046835,0,321951.84,0.174559,0.00,321951.84,"Fri, 15 Feb 2036 00:00:00 GMT",4429.62,0.013498,144,144,"Fri, 15 Feb 2036 00:00:00 GMT",20200000.0,20200000.0,317522.22,46361064.96

#### Soma do principal restante após o pagamento da primeira parcela

In [12]:
df['principal'].iloc[1:].sum()

20141553.08

# Segunda Parcela - definindo os valores

In [17]:
Valor2 = df['principal'].iloc[1:].sum() # soma do principal
DataDesembolso = '15-03-2024'
DataPagamento = '15-04-2024'
Tempo = Tempo - 1

In [21]:
url = f'https://install-app-prod.hmg.gyramais.com.br/installapp/priceTableTabular/?preApproved={Valor2}&Period={Tempo}&interestRate={TaxaJuros}&DisbursementDate={DataDesembolso}&PaymentDate={DataPagamento}&Partner=Gyra&IPCA=True&Fees=False&Iof=False&AdjustedIof=True'

In [22]:
_json_ = requests.get(url)

In [23]:
pd.json_normalize(_json_.json())

,DisbursementDate,IPCA,Iof,amortization_amount,annualCet,balance,installAmount,installDates,interest,interestRate,months,number,payDayDates,preApproved,preApprovedWithFees,principal,totalFinalAmount
0,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,20059624.26,321951.85,"Mon, 15 Apr 2024 00:00:00 GMT",280987.44,0.013498,143,1,"Mon, 15 Apr 2024 00:00:00 GMT",20141553.08,20141553.08,40964.41,46039114.55
1,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,19999303.99,321951.85,"Wed, 15 May 2024 00:00:00 GMT",271309.51,0.013498,143,2,"Wed, 15 May 2024 00:00:00 GMT",20141553.08,20141553.08,50642.34,46039114.55
2,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,19965461.56,321951.85,"Sat, 15 Jun 2024 00:00:00 GMT",279709.47,0.013498,143,3,"Mon, 17 Jun 2024 00:00:00 GMT",20141553.08,20141553.08,42242.38,46039114.55
3,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,19903911.83,321951.85,"Mon, 15 Jul 2024 00:00:00 GMT",270055.79,0.013498,143,4,"Mon, 15 Jul 2024 00:00:00 GMT",20141553.08,20141553.08,51896.06,46039114.55
4,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,19868696.54,321951.85,"Thu, 15 Aug 2024 00:00:00 GMT",278396.18,0.013498,143,5,"Thu, 15 Aug 2024 00:00:00 GMT",20141553.08,20141553.08,43555.67,46039114.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,943442.31,321951.85,"Mon, 15 Oct 2035 00:00:00 GMT",20862.17,0.013498,143,139,"Mon, 15 Oct 2035 00:00:00 GMT",20141553.08,20141553.08,301089.68,46039114.55
139,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,635352.31,321951.85,"Thu, 15 Nov 2035 00:00:00 GMT",17362.01,0.013498,143,140,"Thu, 15 Nov 2035 00:00:00 GMT",20141553.08,20141553.08,304589.84,46039114.55
140,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,321412.36,321951.85,"Sat, 15 Dec 2035 00:00:00 GMT",12686.95,0.013498,143,141,"Mon, 17 Dec 2035 00:00:00 GMT",20141553.08,20141553.08,309264.90,46039114.55
141,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,4370.25,321951.85,"Tue, 15 Jan 2036 00:00:00 GMT",8798.35,0.013498,143,142,"Tue, 15 Jan 2036 00:00:00 GMT",20141553.08,20141553.08,313153.50,46039114.55
142,"Fri, 15 Mar 2024 00:00:00 GMT",0.046835,0,321951.85,0.174559,0.00,321951.85,"Fri, 15 Feb 2036 00:00:00 GMT",4429.66,0.013498,143,143,"Fri, 15 Feb 2036 00:00:00 GMT",20141553.08,20141553.08,317522.19,46039114.55

In [24]:
df2 = pd.json_normalize(_json_.json())

In [25]:
df2['principal'].sum()

20141551.5

# Terceira Parcela - definindo os valores

In [26]:
Valor3 = df2['principal'].iloc[1:].sum() # soma do principal
DataDesembolso = '15-04-2024'
DataPagamento = '15-05-2024'
Tempo = Tempo - 1

In [31]:
url = f'https://install-app-prod.hmg.gyramais.com.br/installapp/priceTableTabular/?preApproved={Valor3}&Period={Tempo}&interestRate={TaxaJuros}&DisbursementDate={DataDesembolso}&PaymentDate={DataPagamento}&Partner=Gyra&IPCA=True&Fees=False&Iof=False&AdjustedIof=True'

In [32]:
_json_ = requests.get(url)

In [34]:
pd.json_normalize(_json_.json())

,DisbursementDate,IPCA,Iof,amortization_amount,annualCet,balance,installAmount,installDates,interest,interestRate,months,number,payDayDates,preApproved,preApprovedWithFees,principal,totalFinalAmount
0,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,19999302.41,321951.83,"Wed, 15 May 2024 00:00:00 GMT",271309.49,0.013498,142,1,"Wed, 15 May 2024 00:00:00 GMT",20100587.09,20100587.09,50642.34,45717159.86
1,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,19965459.98,321951.83,"Sat, 15 Jun 2024 00:00:00 GMT",279709.44,0.013498,142,2,"Mon, 17 Jun 2024 00:00:00 GMT",20100587.09,20100587.09,42242.39,45717159.86
2,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,19903910.25,321951.83,"Mon, 15 Jul 2024 00:00:00 GMT",270055.77,0.013498,142,3,"Mon, 15 Jul 2024 00:00:00 GMT",20100587.09,20100587.09,51896.06,45717159.86
3,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,19868694.95,321951.83,"Thu, 15 Aug 2024 00:00:00 GMT",278396.15,0.013498,142,4,"Thu, 15 Aug 2024 00:00:00 GMT",20100587.09,20100587.09,43555.68,45717159.86
4,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,19823924.02,321951.83,"Sun, 15 Sep 2024 00:00:00 GMT",277788.52,0.013498,142,5,"Mon, 16 Sep 2024 00:00:00 GMT",20100587.09,20100587.09,44163.31,45717159.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,943440.07,321951.83,"Mon, 15 Oct 2035 00:00:00 GMT",20862.14,0.013498,142,138,"Mon, 15 Oct 2035 00:00:00 GMT",20100587.09,20100587.09,301089.69,45717159.86
138,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,635350.06,321951.83,"Thu, 15 Nov 2035 00:00:00 GMT",17361.98,0.013498,142,139,"Thu, 15 Nov 2035 00:00:00 GMT",20100587.09,20100587.09,304589.85,45717159.86
139,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,321410.10,321951.83,"Sat, 15 Dec 2035 00:00:00 GMT",12686.92,0.013498,142,140,"Mon, 17 Dec 2035 00:00:00 GMT",20100587.09,20100587.09,309264.91,45717159.86
140,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,4367.98,321951.83,"Tue, 15 Jan 2036 00:00:00 GMT",8798.32,0.013498,142,141,"Tue, 15 Jan 2036 00:00:00 GMT",20100587.09,20100587.09,313153.51,45717159.86
141,"Mon, 15 Apr 2024 00:00:00 GMT",0.046835,0,321951.83,0.174559,0.00,321951.83,"Fri, 15 Feb 2036 00:00:00 GMT",4429.63,0.013498,142,142,"Fri, 15 Feb 2036 00:00:00 GMT",20100587.09,20100587.09,317522.20,45717159.86

# Observar que, em todas as parcelas o valor de 'amortization_amount' não mudou mesmo mudando o tempo e as datas. Isso ocorre por causa do IPCA que não alterou e corrobora com o estudo de caso de como o sistema deve funcionar.